name = "34th PRC Aux Mod"
author = "34th PRC Aux Mod Team"
prefix = "34thPRC"
mainprefix = "z"

[version]
path = "addons/34thPRC_Main/script_version.hpp"

[files]
include = [
    "34thPRC_logo.paa",
    "changelog.md",
    "mod.cpp",
]

[hemtt.release]
folder = "34th PRC Aux Mod"