name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: peterjgrainger/action-changelog-reminder@v1.3.0
        with:
          # A regex to match changelog file, default to 'change_log\/.*\/*.yml'
          changelog_regex: "changelog.md"
          # Custom message to display if no changelong is found
          customPrMessage: "Does the changelog need updating in this pull request?"
            
