name: "Editor Config Checker"
on:
- pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: zbeekman/EditorConfig-Action@v1.1.0
          
