name: "Editor Config Checker"
on:
- pull_request_target

jobs:
  editorconfig-check:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: editorconfig-checker/action-editorconfig-checker@v1.0.0
          
