name: "Editor Config Enforcer"
on:
- pull_request

jobs:
  editer-config-enforcer:
    permissions:
      contents: read
    #  pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: kasperhesthaven/setup-editorconfig-checker@v1.2.0
    - uses: greut/eclint-action@v0
    # - uses: editorconfig-checker/action-editorconfig-checker@v1.0.0
    # - uses: snow-actions/eclint@v1.0.1
