name: "Editor Config Enforcer"
on:
- pull_request

jobs:
  editer-config-enforcer:
    permissions:
      contents: read
    #  pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: zbeekman/EditorConfig-Action@28b76e718c351dd35b22c8f7216192bb9de5c21b
