name: "HEMTT Build"
on:
- pull_request

jobs:
  hemtt-build:
    permissions:
      contents: read
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - run: winget install hemtt
    - name: Steam - Download
      # You may pin to the exact commit or the version.
      # uses: dhkatz/steam-download@347034b27197b9937f6e0f871b5aad5bec0cdb04
      uses: dhkatz/steam-download@v1.2.0
      with:
        # Steam username
        #username: # default is anonymous
        # Steam password
        #password: # optional
        # Steam TOTP code
        #totp: # optional
        # Path to VDF file containing login details
        #vdf: # optional
        # Steam AppID
        appid: 233800 # https://store.steampowered.com/app/233800/Arma_3_Tools/
        # Path to download the game to
        #path: # optional
    - run: .\build.bat
