name: Prep Release

on:
  pull_request_target:
    types: [opened, labeled, synchronize, reopened]
    branches:
      - '*'

jobs:
  prep-release:
    runs-on: windows-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: debug
      id: debug
      shell: pwsh
      run: |
        $labels = ${{github.event.pull_request.labels}} | ForEach-Object { $_.name }

        $labels | ForEach-Object { Write-Output $_ }



        exit 1

    - name: Check for release label
      id: check_label
      shell: pwsh
      env:
        PR_LABELS: ${{ github.event.pull_request.labels }}
      run: |
        if ($labels -notcontains 'release') {
          Write-Output "No release label found. Exiting."
          exit 0
        }
    - name: Checkout repository
      if: steps.check_label.outputs.label_found == 'true'
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Run prepRelease.ps1
      if: steps.check_label.outputs.label_found == 'true'
      run: pwsh ./prepRelease.ps1 -CI
      continue-on-error: false

    - name: Commit and push changes
      if: steps.check_label.outputs.label_found == 'true' && success()
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Automated prep release"
        branch: ${{ github.head_ref }}
        token: ${{ secrets.GITHUB_TOKEN }}
