name: Prep Release

on:
  pull_request:
    types: [opened, labeled, synchronize]
    branches:
      - '*'

jobs:
  prep-release:
    if: ${{contains(github.event.pull_request.labels.*.name, 'release')}}
    runs-on: windows-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Run prepRelease.ps1
      run: pwsh ./prepRelease.ps1 -CI
      continue-on-error: false

    - name: Commit and push changes
      if: success()
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Automated prep release"
        branch: ${{ github.head_ref }}
        token: ${{ secrets.GITHUB_TOKEN }}
