name: "Release Reminder"

on:
  pull_request_target:
  pullrequest:
    types:
      - opened
      - labeled

jobs:
  release-reminder:
    if: ${{ github.event.pull_request.labels.*.name == 'release' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: "Did you bump the verion in the main PBO?"
