name: "Release Reminder"
on:
  pull_request_target:
    types: [opened, labeled, synchronize]
    branches:
      - '*'

jobs:
  release-reminder:
    if: ${{contains(github.event.pull_request.labels.*.name, 'release')}}
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: mskelton/changelog-reminder-action@v3.0.0
      with:
        changelogRegex: "src/changelog.md"
        message: "Did you bump the version number in the main PBO?"
